CREATE TABLE Roles (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Users (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	RoleID INT NOT NULL,
	Username VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Gender VARCHAR(50) NOT NULL,

	FOREIGN KEY (RoleID) REFERENCES Roles(ID)
);

CREATE TABLE Meats (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Ramens (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	MeatID INT NOT NULL,
        Broth VARCHAR(50) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Price INT NOT NULL,

	FOREIGN KEY (MeatID) REFERENCES Meats(ID)
);

CREATE TABLE TransactionHeaders (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	CustomerID INT NOT NULL,
	StaffID INT NOT NULL,
	Date DATE NOT NULL,

	FOREIGN KEY (CustomerID) REFERENCES Users(ID),
	FOREIGN KEY (StaffID) REFERENCES Users(ID)
);

CREATE TABLE TransactionDetails (
	HeaderID INT NOT NULL,
	RamenID INT NOT NULL,
	Quantity INT NOT NULL,

	FOREIGN KEY (HeaderID) REFERENCES TransactionHeaders(ID),
	FOREIGN KEY (RamenID) REFERENCES Ramens(ID),
	PRIMARY KEY (HeaderID, RamenID)
);
